### PR TITLE
Updated UI/UX

### PR DESCRIPTION
**Pull request by McTechie**
- Changed **mini-box** sizes to maintain uniformity.
- Changed design of the **testimonials-item** to better suit the theme, and maintain uniformity.
- Added **social-icon buttons** in the footer and at the right.

### CODE REVIEW

**Review by priyanshisharma — COMMENTED** [review]
I checked it out, I appreciate adding the missing pieces in the social media buttons.

In the testimonial section, *Parjanya Shukla* looks a little highlighted, could you justify that? Because the uneven lengths did bother me, but I don't want to highlight like that, seems partial.

**Comment by ExpressHermes** [comment]
@priyanshisharma uneven lengths are an issue for us. It breaks the over all structure and symmetry of the section.

**Comment by McTechie** [comment]
Sure will do 👍🏼

**Comment by McTechie** [comment]
Changed the design of all the Testimonials to look the same, and fixed the altered sizes issue.

**Comment by priyanshisharma** [comment]
@ExpressHermes but what if we change the testimonials later? We'll need to change the design too? 😅

**Review by priyanshisharma — APPROVED** [review]
I just checked it again, and I'm happy with it now 😄 we can merge this 🚀

**Comment by ExpressHermes** [comment]
@priyanshisharma for future testimonials we can create a carousel.

**Comment by priyanshisharma** [comment]
Okay @ExpressHermes , are you happy with this PR rn? If yes, I think we should merge it.

**Review by ExpressHermes — APPROVED** [review]
Good work @mcs-codes!

**Pull request merged**
