### PR TITLE
Please review the changes and merge

### PR DESCRIPTION
**Pull request by bhatiashivam**
-----------------------------
DONE
-----------------------------

- change header item 'Pricing Tables' to 'Find us'
- embed 3 Instagram posts
- change 'Let’s discuss about you project' to 'Let’s discuss about your project'

-----------------------------
TO DO
-----------------------------

- social media icons > aside right - increase size
- social media icons > footer >  increase size
- all divs equal size > our initiatives
- all divs equal size > what do they say
- modify text > speaker sessions
- logo >  increase size

### CODE REVIEW

**Review by ExpressHermes — CHANGES_REQUESTED** [review]
Resolve the conflicts @bhatiashivam

**Review by priyanshisharma — COMMENTED** [review]
Screen Shot 2020-10-11 at 6 43 47 PM

Is it possible to see the thumbnail itself, rather than *View this post on Instagram*

**Review by priyanshisharma — CHANGES_REQUESTED** [review]
Conflicts have not been correctly resolved, eg.
*  testimonials are incorrectly put . 
Screen Shot 2020-10-12 at 1 14 34 PM

*  Instagram is missing altogether
*  27 countries should not be there

Screen Shot 2020-10-12 at 1 18 08 PM

### **Please don't merge this and fix this.**

**Review by ExpressHermes — CHANGES_REQUESTED** [review]
img 1
img 2
img 3

These sections are broken and contain redundant code. Can you please refactor them? Please pull the latest dev branch before refactoring as some of the changes have already been resolved.

**Pull request closed without merging**
